// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1xHo2A3ejT7JU_ErQtwtSTTK0dM6yjL0',
    appId: '1:439074732981:web:129452cefb453101c237fc',
    messagingSenderId: '439074732981',
    projectId: 'dispose-9ffc6',
    authDomain: 'dispose-9ffc6.firebaseapp.com',
    storageBucket: 'dispose-9ffc6.appspot.com',
    measurementId: 'G-VRH697WJW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC24ZR0M9_0S-xe4WNHBA9sU5i5qKKR2yo',
    appId: '1:439074732981:android:f0ba098401dfc9a9c237fc',
    messagingSenderId: '439074732981',
    projectId: 'dispose-9ffc6',
    storageBucket: 'dispose-9ffc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx8JqrL85a6BMdH0h94BMv9V8bUY9UXps',
    appId: '1:439074732981:ios:de9fa7d87084cf90c237fc',
    messagingSenderId: '439074732981',
    projectId: 'dispose-9ffc6',
    storageBucket: 'dispose-9ffc6.appspot.com',
    iosClientId: '439074732981-m5jd8365vi1c86gsqd01p5kietunucba.apps.googleusercontent.com',
    iosBundleId: 'ir.dispose.dongi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx8JqrL85a6BMdH0h94BMv9V8bUY9UXps',
    appId: '1:439074732981:ios:de9fa7d87084cf90c237fc',
    messagingSenderId: '439074732981',
    projectId: 'dispose-9ffc6',
    storageBucket: 'dispose-9ffc6.appspot.com',
    iosClientId: '439074732981-m5jd8365vi1c86gsqd01p5kietunucba.apps.googleusercontent.com',
    iosBundleId: 'ir.dispose.dongi',
  );
}
