// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3L59Fr2Q8V8FpLgRuhxZOPNZANiDRYFw',
    appId: '1:323276056333:web:7044dc6c1e70c522a7f244',
    messagingSenderId: '323276056333',
    projectId: 'dispose-ef178',
    authDomain: 'dispose-ef178.firebaseapp.com',
    storageBucket: 'dispose-ef178.appspot.com',
    measurementId: 'G-3F2506X0NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4WoE17d_tsdNg2oi5UppRe7gvqcklpu4',
    appId: '1:323276056333:android:cab2b0509a94ef61a7f244',
    messagingSenderId: '323276056333',
    projectId: 'dispose-ef178',
    storageBucket: 'dispose-ef178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4REgtZ6cY7Dt9FkWfigX3dtTB_k48IQo',
    appId: '1:323276056333:ios:454aeba2ee4a2e2ca7f244',
    messagingSenderId: '323276056333',
    projectId: 'dispose-ef178',
    storageBucket: 'dispose-ef178.appspot.com',
    iosClientId: '323276056333-b85v25ec4iehasu005hvq6k2t6emlumv.apps.googleusercontent.com',
    iosBundleId: 'ir.dispose.dongi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4REgtZ6cY7Dt9FkWfigX3dtTB_k48IQo',
    appId: '1:323276056333:ios:454aeba2ee4a2e2ca7f244',
    messagingSenderId: '323276056333',
    projectId: 'dispose-ef178',
    storageBucket: 'dispose-ef178.appspot.com',
    iosClientId: '323276056333-b85v25ec4iehasu005hvq6k2t6emlumv.apps.googleusercontent.com',
    iosBundleId: 'ir.dispose.dongi',
  );
}
